  Apis-Rest[m
* [32mArquitetura-Limpa[m
  Arquitetura-software-1[m
  Arquitetura-software-2[m
  Classes_e_Encapsulamento[m
  Criptografia_User[m
  Express.js[m
  Intro-Typescript[m
  MySQL-Markdown[m
  Polimorfismo[m
  Relacoes-em-SQL[m
  Ytalo-Pokedex[m
  ][m
  intro-autenticacao[m
  labecommerce[m
  master[m
  semana10-labeX[m
  semana12-LabEddit[m
  semana6-aula22[m
  semana7-aula24[m
  semana7-aula25[m
  semana7-aula27[m
  semana7-labefy[m
  semana9-Astromatch[m
  semana9-aula31[m
  semana9-aula32[m
